### ISSUE TITLE
version: latest is installing v1.64.0 instead of 2.1.0

### ISSUE THREAD

**Issue by CloudHeadedJA** [digitalocean/action-doctl#52]
Using the snippet provided here: https://github.com/digitalocean/action-doctl#usage

`    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
`
Installation of doctl succeeds but an incorrect version is installed.

Expecting version 2.1.0 (latest)
Version 1.64.0 is installed instead.

> Run digitalocean/action-doctl@v2
  with:
    token: ***
    version: latest
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/c2ae0e11-6ec8-4463-8038-7d9677ae74dd -f /home/runner/work/_temp/532dec3b-d30c-4230-bb01-fff68e70f25b
>>> doctl version v1.64.0 installed to /opt/hostedtoolcache/doctl/1.64.0/x64
/opt/hostedtoolcache/doctl/1.64.0/x64/doctl auth init -t ***

**Comment by andrewsomething** [comment]
Hi @CloudHeadedJA,

v1.64.0 is the latest version of `doctl` itself:

https://github.com/digitalocean/doctl/releases

**Comment by CloudHeadedJA** [comment]
Apologies. Confused between the list of available marketplace versions of "GitHub Action for DigitalOcean - doctl" vs the actual doctl version. 

Thanks for clarifying.
