### ISSUE TITLE
Usage instructions should have a token setup reminder

### ISSUE THREAD

**Issue by CloudHeadedJA** [digitalocean/action-doctl#53]
May be worth providing a reminder in the [Usage section](https://github.com/marketplace/actions/github-action-for-digitalocean-doctl#usage) or a pre-requisite section that directing users to set up a DigitalOcean API token and add it as a GitHub repo or organization secret prior to usage steps. 

Details on doing so are certainly out of scope but a friendly reminder could save newer users some setup time.

**Comment by CloudHeadedJA** [comment]
Thanks @andrewsomething

**Comment by andrewsomething** [comment]
No problem! Thanks for suggesting it @CloudHeadedJA
