### ISSUE TITLE
Ignore file

### ISSUE THREAD

**Issue by bensonarafat** [digitalocean/action-doctl#69]
How can i ignore some files?
Thanks

**Comment by bentranter** [comment]
Hey @bensonarafat, this project is a GitHub Action for using `doctl`, DigitalOcean's CLI tool. Ignoring files isn't a necessary feature of the tool or this GitHub Action. I'm going to close this, but if you have a more specific issue or question around ignoring files, please feel free to comment and re-open. Thanks!
