### ISSUE TITLE
Update login to use new limited scopes for token

### ISSUE THREAD

**Issue by kenkendk** [digitalocean/action-doctl#83]
The login action currently requests scope "read write", meaning a "full access" token is required.
Digital Ocean access tokens now supports more granular scopes, but using a token with only read+update on registry fails, because the auth requests too broad a scope:

```
Run doctl registry login --expiry-seconds 1200
  doctl registry login --expiry-seconds 1200
  shell: /usr/bin/bash -e {0}
Logging Docker in to registry.digitalocean.com
Error: GET https://api.digitalocean.com/v2/registry/docker-credentials?expiry_seconds=1200&read_write=true: 403 (request "34fe003d-496e-4c9e-b689-558c7396b9e3") you do not have access for the attempted action
Error: Process completed with exit code 1.
```

**Comment by andrewsomething** [comment]
By default `doctl registry login` attempts to log you into the registry with full read/write access which requires the `registry:create` scope. If you only want read-only access to the registry, you need to include the `--read-only` flag.

```
doctl registry login --expiry-seconds 1200 --read-only
```

**Comment by kenkendk** [comment]
Thanks @andrewsomething I needed the `registry:create` permission. 

The error message and call made it appear to me as if I needed full-account read+write permissions, which would be "problematic".

**Comment by andrewsomething** [comment]
Glad to help!
